name: CI
on: [push]

jobs:
 sast_scan:
  name: Run Gosec
  runs-on: ubuntu-latest

  steps:
  - name: Checkout Code
    uses: actions/checkout@v5.0.0

  - name: Install Go
    uses: actions/setup-go@v6.0.0
    with: 
      go-version: 1.23.2
  - name: Install gosec
    run: go install github.com/securego/gosec/v2/cmd/gosec@v2.22.5
    
  - name: Run gosec
    run: gosec -fmt json -out results.json ./.. 
  - name: Upload Report
    uses: actions/upload-artifact@v4.6.2
    if: always()
    with:
     name: gosec report
     path: results.sarif

      
    
  
  
  
 
 

